variable region {}
variable profile {}
variable env {}
variable color {}
variable application {}
variable created_by {}
variable dns_zone_id {}
variable viewer_certificate {}
variable comment {}
variable domain {}
variable lambda_invoke_arn {}
variable lambda_name {}